### ISSUE TITLE
Draft "Running tests in parallel"

### ISSUE THREAD

**Issue by robertodr** [bast/cmake-recipes#108]

**Comment by bast** [comment]
I don't think this warrants own recipe. I will discuss this as part of other testing recipes. Will close this as soon as it is integrated somewhere. Considering rather adding a recipe on how to test compiled code with pytest assisted by CMake. This is very relevant in particular for Fortran folks IMO.

**Comment by bast** [comment]
In any case mention COST property where-ever I discuss the parallel testing: https://cmake.org/cmake/help/v3.3/prop_test/COST.html. Might actually warrant own recipe after all.

**Comment by robertodr** [comment]
Neat!

**Comment by bast** [comment]
Note to self when writing the text (ascii will become proper graphics):
```
tests and their duration:
a b c d e f g h i j
1 1 1 1 3 3 3 5 7 9

stacking on 4 cores without COST:
aeeeiiiiiii
bfffjjjjjjjjj
cggg
dhhhhh
1234567890123

stacking on 4 cores with COST:
jjjjjjjjj
iiiiiiibd
hhhhhggg
eeefffac
123456789
```

**Comment by bast** [comment]
Draft complete.
