### ISSUE TITLE
Consider adding "how to find Valgrind" example to chapter “Detecting external libraries and programs”

### ISSUE THREAD

**Issue by bast** [bast/cmake-recipes#125]
Chapter 3 is called “Detecting external libraries and programs” yet I only showed how to find one program: the Python interpreter. Roberto suggests there should be an additional recipe showing how to find Valgrind.

**Comment by bast** [comment]
Thumbs up from me for that!

**Comment by bast** [comment]
To offer a counter-argument: we now detect Valgrind in the memcheck recipe (testing chapter). Should we still add this to chapter 3? @robertodr

**Comment by robertodr** [comment]
No, I think we're doing good as-is :+1:

**Comment by bast** [comment]
Great. Closing.
