### ISSUE TITLE
[Discussion] Update CMake requirement to 3.3?

### ISSUE THREAD

**Issue by robertodr** [bast/cmake-recipes#138]
This version added `CheckFortranCompilerFlag.cmake`

**Comment by bast** [comment]
Good idea. Thumbs up.

**Comment by robertodr** [comment]
If you have any other features in mind from later versions, list them here. We should have an auction :smiley: We could also go for the latest already. Frankly, it's so easy to install CMake that juggling version numbers is more time-consuming.

**Comment by bast** [comment]
We can go for the latest to make it simple. It is simple to install and then the book is longer lived, too. Currently no other modern features in my mind but I would go for the latest.

**Comment by robertodr** [comment]
https://cmake.org/cmake/help/v3.10/release/3.10.html Yeah, this looks very cool. Especially `FindOpenACC.cmake` and the overhaul of `FindMPI.cmake` and `FindOpenMP.cmake` We will have to rewrite those recipes, but they will look much simpler.

**Comment by bast** [comment]
Awesome!

**Comment by bast** [comment]
Has this issue been now solved with https://github.com/bast/cmake-recipes/commit/d28c91b33a477ca69eb7ffca9007254b53c15b9f?

**Comment by robertodr** [comment]
Only partially, because I didn't make the change in the `CMakeLists.txt` of the recipes.

**Comment by bast** [comment]
Is that all that remains? If yes, I can take care of that.

**Comment by bast** [comment]
Sadly I don't manage to get the latest version on OS X: https://github.com/bast/cmake-recipes/commit/6b75afae26687199c219de506b8b0c89ed7c4aba
Alternative is to build CMake from sources on Mac. What do you think?

**Comment by bast** [comment]
Update: finally got CMake 3.10 installed on Mac. Disregard the above. PR coming up in a moment.
