### ISSUE TITLE
[Notes] 3.10 features to mention/employ

### ISSUE THREAD

**Issue by bast** [bast/cmake-recipes#142]
Just so that we don't lose this from #138. See also https://cmake.org/cmake/help/v3.10/release/3.10.html
- [ ] FindOpenACC.cmake
- [ ] Overhaul of FindMPI.cmake and FindOpenMP.cmake (we will have to rewrite those recipes)
- [x] https://cmake.org/cmake/help/v3.10/command/cmake_host_system_information.html

**Comment by bast** [comment]
I guess we are not doing FindOpenACC.cmake?
What is there left to do in terms of FindMPI or FindOpenMP?

**Comment by robertodr** [comment]
- We can't test OpenACC on our CI infrastructure, so I'd just mention it in the OpenMP recipe (or any other place that you think more relevant would do) 
- OpenMP and MPI: I think both have to be rewritten in terms of imported targets. For MPI you did it already, isn't it?

**Comment by bast** [comment]
OK - yes, MPI is done but typecloud is out of sync but that is fine, I plan to do a full sweep comparing everything.

**Comment by bast** [comment]
Done.
