### ISSUE TITLE
Recipe "Detecting the Eigen Library" fails with Unix Makefiles

### ISSUE THREAD

**Issue by bast** [bast/cmake-recipes#147]
This is not Travis' fault. Fails also for me locally. First it seems that we don't link against detected LAPACK. But once that is fixed it also looks like this example requires LAPACKE which is not detected by FindLAPACK.

**Comment by bast** [comment]
@robertodr can you please try whether you reproduce this locally with Unix Makefiles? Test passes with Ninja.

**Comment by robertodr** [comment]
I'll look into this. It's really weird: it started making trouble when HDF5 was fiddled with...

**Comment by bast** [comment]
I believe this one is fixed now.
