### ISSUE TITLE
Discover math libraries: show MKL and ScaLAPACK

### ISSUE THREAD

**Issue by robertodr** [bast/cmake-recipes#15]
This will need the Drone instance for testing.
### Requirements
- If C/CXX are enabled, it should also find headers for CBLAS and LAPACKE
- Possible example [here](https://bitbucket.org/eigen/eigen/src/699b6595fc471456896fb27193c8ca51389b7850/cmake/FindBLAS.cmake?at=default&fileviewer=file-view-default) for BLAS.
- Possible example [here](https://bitbucket.org/eigen/eigen/src/699b6595fc471456896fb27193c8ca51389b7850/cmake/FindLAPACK.cmake?at=default&fileviewer=file-view-default) for LAPACK.

**Comment by bast** [comment]
This will be a very useful example.

**Comment by bast** [comment]
As a note to myself this will be part of writing own functions (I need to give names to chapter numbers).

**Comment by robertodr** [comment]
Feel free to rename milestones and projects. I followed the path of least work :smile_cat:

**Comment by bast** [comment]
Followed-up in https://github.com/coderefinery/autocmake/issues/246.
