### ISSUE TITLE
Update Eigen recipe on TypeCloud

### ISSUE THREAD

**Issue by bast** [bast/cmake-recipes#156]
Context: #155

**Comment by bast** [comment]
Unassigned myself - I compared the two but notice that the text will change as well, not just code blocks and it is better if you implement the change since you know better what you had in mind.

**Comment by robertodr** [comment]
Yes, I used the new OpenMP target since I was at it. After compiling LAPACKE I found out that `FindLapack` can't find it and I didn't want to hard code linking to it. I just scrapped that optional part.

**Comment by bast** [comment]
Following up outside. Closing.
