### ISSUE TITLE
False positives on Travis

### ISSUE THREAD

**Issue by robertodr** [bast/cmake-recipes#168]
- Builds of Fortran examples do not report `building ... OK` with `Unix Makefiles` as generators.
- Chapter 1, recipe 10, C++ example requires C++14. GCC 4.8 is not feature-complete and the build fails, but it still reports the build as OK.
- Chapter 3, recipe 4, C++ example fails to link against BLAS/LAPACK. Build fails, but is still reported as OK.
- Chapter 3, recipe 9, Fortran example. Still can't find Fortran 2003 binding, I have to debug the CMake code for that.
- Chapter 5, recipe 3, C++ example. Can't link against BLAS/LAPACK
- Chapter 5, recipe 4, C++ example. Can't link against BLAS/LAPACK

**Comment by bast** [comment]
Thanks! I will try to reproduce this.

**Comment by robertodr** [comment]
P.S. Locally everything looks fine...

**Comment by bast** [comment]
OK so locally they pass but in the cloud they fail and we don't know about it because the script swallows the problem?

**Comment by robertodr** [comment]
Exactly

**Comment by bast** [comment]
It's because we check for strings like "Built target" which say nothing about the whole step completing :-) Switching soon to return codes.

**Comment by bast** [comment]
PR #170 exposes all problems except Chapter 3, recipe 9, Fortran example but I guess this is not the script's fault unless we let the code fail with FATAL_ERROR if the functionality is not there.

**Comment by bast** [comment]
Remaining issue followed up in #171. Closing this one.
