### ISSUE TITLE
Chapter 3, recipe 9, Fortran example: Still can't find Fortran 2003 binding

### ISSUE THREAD

**Issue by bast** [bast/cmake-recipes#171]
Test passes but does not detect 2003.

**Comment by robertodr** [comment]
It's supposed to work that way, meaning that if Fortran 2003 is not found, the source code depending on it won't be compiled. I was more concerned that Fortran recipes did not show the `building ... OK` string even though they were being built.

**Comment by bast** [comment]
Aha - I see the issue. It still does not show it. I need to investigate why.

**Comment by robertodr** [comment]
Sorry, I can see how the original description was kind of confusing.

**Comment by bast** [comment]
"Nothing to be done" is a bad skip predicate since the main target can have sub-targets. Back to the drawing board.
