### ISSUE TITLE
[Discussion] code repetition of menu.yml

### ISSUE THREAD

**Issue by bast** [bast/cmake-recipes#180]
Pro: fine grain, cons: enormous code repetition. AFAICS compilers stay constant for each testing platform. Should we keep the current scheme or abstract this better? It's a bit of a pain that if you want to switch compilers you have to edit many menu.yml files which creates diff noise.

**Comment by bast** [comment]
To be more specific: I am not suggesting getting rid of `menu.yml`s. They are good for tweaks and skips but I think we should specify the compilers more globally unless you foresee a situation where we want to deviate from a global setting for a recipe.

**Comment by robertodr** [comment]
I see what you mean and I agree. Explicit is better than implicit, until it becomes a pain in the ***. How would you do that though?

**Comment by bast** [comment]
How about we keep the menu files and they override everything but we have a global setting for compilers in the main CI script which the script defaults to if nothing is set in the menu files?

**Comment by bast** [comment]
Or how about a global `menu.yml` with same structure that is the default for things and local menu.yml override settings, if present.

**Comment by robertodr** [comment]
Second approach sounds better IMO
