### ISSUE TITLE
CI script

### ISSUE THREAD

**Issue by robertodr** [bast/cmake-recipes#2]
The CI script is very simple-minded. Things to improve:
1. The report dumps all info to screen. Should we agree on a less cluttered output format? **EDIT** I have also noticed that non-`STATUS` messages from CMake are printed elsewhere from where you'd expect (separate from the CMake configuration output stream) I suspect CMake might use the stderr instead of stdout for these.
2. Some of the failing builds, fail the whole CI. But maybe we want to show that some stuff doesn't work. How can we implement an "expected failure" behavior?
3. It would be good to move the environment variables inside the various subdirectories. I think this will contribute to have cleaner build matrices on the CI services. I have played around with `direnv` to no avail. Maybe I can get you up to speed with what I've done, before we decide the next steps.

**Comment by bast** [comment]
All 3 suggestions sound good. Indeed I need to get a bit up to speed first. I will look around in the scripts to get a grasp and then return to this discussion.

**Comment by robertodr** [comment]
It works for now, but it could be better. I opened the issue as a reminder to self :wink:

**Comment by bast** [comment]
I like the yaml idea :-) I start working on the recipes/book this weekend.

**Comment by robertodr** [comment]
I think it is necessary to do this to get meaningful recipes. For example, I can't modify the compiler for just one recipe with `-DCMAKE_<LANG>_COMPILER=blabla` without doing so for all recipes. If you can do a first pass, I would be grateful (time will be a bit tight for me in the next couple of weeks)

**Comment by bast** [comment]
I will implement this. Now it's my turn to also do something.

**Comment by bast** [comment]
1) done (PR not submitted yet but soon)
2) split out to own issue: #33
3) to be done (once it is done will file a PR)
