### ISSUE TITLE
Change foreach example to not encourage globbing sources

### ISSUE THREAD

**Issue by bast** [bast/cmake-recipes#200]
I recommend to move the foreach example to the end of the chapter and to perhaps apply it on an example where optimization for a couple of sources needs to be lowered. IMO the current glob example can encourage bad practice (although this is mentioned later).
One idea could be to show how to lower optimization on a couple of source files without introducing new targets (sometimes source files with different opt needs belong to one target).

**Comment by TheErk** [comment]
I would advise not to use file(GLOB ...) in the first place or any not recommended feature.
Not recommended but "legacy" used feature like that may be mentionned as "compatibilty recipe" or "legacy recipe" but they are not first class recipe candidate (my opinion though).

**Comment by bast** [comment]
I agree - we will change this recipe and only mention that file(GLOB ...) exists and explain why this is not recommended practice.
