### ISSUE TITLE
Prepare Docker image for PGI toolstack

### ISSUE THREAD

**Issue by robertodr** [bast/cmake-recipes#21]

**Comment by robertodr** [comment]
Working on this https://github.com/robertodr/dockerfiles

**Comment by bast** [comment]
Should we really support PGI stack? How about we restrict ourselves to Intel and GNU?

**Comment by robertodr** [comment]
I don't know. I have the Docker image ready though.

**Comment by bast** [comment]
OK if it is no extra work, then I have nothing against that - it might help detecting structures which are not portable.

**Comment by robertodr** [comment]
I'm switching the Fortran recipes to use PGI on Drone. Let's see how that goes.

**Comment by robertodr** [comment]
This is up and running on Drone. Closing.

**Comment by bast** [comment]
Awesome!
