### ISSUE TITLE
Use imported targets

### ISSUE THREAD

**Issue by bast** [bast/cmake-recipes#225]
As demonstrated by Eric in #224.

Left to do:
- [x] Identify recipes which need to be updated.
- [x] Update these recipes.
- [ ] Update typecloud.

**Comment by bast** [comment]
We will synchronize with typecloud anyway in a second iteration.

**Comment by bast** [comment]
I am working on points 1 and 2.

**Comment by robertodr** [comment]
Great, thank you! I had done a cursory check some when Eric pointed it out and I think we were pretty good at using imported targets already :smile:

**Comment by bast** [comment]
I found this: https://github.com/bast/cmake-recipes/blob/master/Chapter03/recipe-06/c-example/CMakeLists.txt#L14-L25 (upcoming PR)

I am not sure this is needed (on my laptop FFTW is broken so I cannot test):
https://github.com/bast/cmake-recipes/blob/master/Chapter07/recipe-04/c-example/src/CMakeLists.txt#L12-L16

**Comment by bast** [comment]
PR for MPI recipe: https://github.com/bast/cmake-recipes/pull/258

**Comment by robertodr** [comment]
FFTW is sadly needed because their CMake config file is broken and only exports the library, not the headers :disappointed:

**Comment by bast** [comment]
OK thanks - good to know - I will add a comment in the code so that I don't forget this fact.

**Comment by bast** [comment]
Done.
