### ISSUE TITLE
Consider appending to PYTHONPATH

### ISSUE THREAD

**Issue by robertodr** [bast/cmake-recipes#227]
Recipes 3, 4, 5 and 6 in chapter 9 overwrite `PYTHONPATH`. This might lead to some unexpected failures in case the test depends on other modules that were already in `PYTHONPATH`. Solution seems to be to use:
```
PYTHONPATH=${SOME_CMAKE_PATH}:$ENV{PYTHONPATH}
```
instead.

**Comment by bast** [comment]
I am a bit unsure whether we want the recipes to depend on the state of the outside environment? If we don't modify the CMake code, I will at least add a note in the text on this but first want to find out whether this is a behavior we really want.

**Comment by bast** [comment]
OK I got convinced that what you suggest is better. I will implement it.
