### ISSUE TITLE
Travis OS X: install CMake from https://cmake.org/download/

### ISSUE THREAD

**Issue by bast** [bast/cmake-recipes#246]
This is to make sure we get more control over the installed version. With brew we otherwise get something. We will need at least two CMake versions on the system - not sure yet how one can switch between both on OS X.

**Comment by bast** [comment]
One thing we can always do is to install from sources, then we have full control. Downside: takes more time but perhaps we can cache.

**Comment by robertodr** [comment]
HDF5 is built from sources and cached on Travis. So yeah, that can be done. What about always having both installed from the precompiled tarball, but only exporting one of the two to `PATH` according to a flag?

**Comment by bast** [comment]
Yes, I would like both installed, ideally from pre-compiled tarball. Perhaps one can easily switch using `$PATH` also on Mac.

**Comment by bast** [comment]
I think it could be tricky to switch between CMake versions in `menu.yml` because it would complicate local testing. How about we test two CMake version using a Travis matrix? On Linux we would have a set of 4 tests, 2 on 3.5, 2 on 3.10 or 3.11.

**Comment by bast** [comment]
It would mean that a couple of tests would be excluded when running on 3.5.

**Comment by robertodr** [comment]
What about using `direnv`?

**Comment by bast** [comment]
I have never used those. How would it look in practice both on CI and locally on our computers?

**Comment by robertodr** [comment]
We would have to add `.envrc` file that exports the correct variables to `PATH` based on some environment variables that are set locally or on Travis. Now that I spell it out it doesn't sound like a great idea, because it duplicates some of the stuff we do in `menu.yml`...

**Comment by bast** [comment]
What do you think about having 4 tests on linux, 2 for each CMake version and on Mac and Windows we leave things as they are? It looks like it is not difficult to have 2 CMake versions also on Mac but I think we would overkill the testing.

**Comment by robertodr** [comment]
I'm fine with that. The 4 tests on Linux can be split between Travis and Drone, so we don't end up waiting ages for CI to finish.

**Comment by bast** [comment]
OK I am working on this. I think it is important that we get the testing of both 3.5 and 3.10 in place not too late.

**Comment by bast** [comment]
I will first start doing this on Travis and later we can move things over to Drone if it becomes too much.

**Comment by bast** [comment]
We now test 3.5 and 3.10. Closing.
