### ISSUE TITLE
How to properly compile an MPI program?

### ISSUE THREAD

**Issue by robertodr** [bast/cmake-recipes#25]
There seems to be two options, which are currently shown in the C++ and C examples for recipe 16 in Chapter 3.

### C++ Example
Use the MPI compiler wrapper. If I do `VERBOSE=1 make` I see the compile line:
```
/nix/store/8f1nmsd4cw7sdk8xrssmkk9zbq26pc2j-openmpi-1.10.1/bin/mpicxx     
-std=c++11 -o CMakeFiles/hello-mpi.dir/hello-mpi.cpp.o 
-c /home/roberto/Workspace/robertodr/cmake-recipes/Chapter03/recipe-0016/cxx-example/hello-mpi.cpp
```
and the link line:
```
/nix/store/8f1nmsd4cw7sdk8xrssmkk9zbq26pc2j-openmpi-1.10.1/bin/mpicxx      
CMakeFiles/hello-mpi.dir/hello-mpi.cpp.o  -o hello-mpi -rdynamic 
```
`mpicxx --showme:compile` shows that the wrapper has added 
```
-I/nix/store/8f1nmsd4cw7sdk8xrssmkk9zbq26pc2j-openmpi-1.10.1/include -pthread
```
`mpicxx --showme:link` shows that the wrapper has added  
```
-pthread -Wl,-rpath -Wl,/nix/store/8f1nmsd4cw7sdk8xrssmkk9zbq26pc2j-openmpi-1.10.1/lib -Wl,--enable-new-dtags -L/nix/store/8f1nmsd4cw7sdk8xrssmkk9zbq26pc2j-openmpi-1.10.1/lib -lmpi_cxx -lmpi
```
### C Example
Use the unwrapped compiler and then prepare the wrapper using CMake using `target_compile_options`, `target_include_directories` and `target_link_libraries`. The compile line is:
```
/nix/store/j1yn1np5g2vgm5yp8qmqg67x8riwy2kr-gcc-wrapper-5.4.0/bin/gcc   
-I/nix/store/8f1nmsd4cw7sdk8xrssmkk9zbq26pc2j-openmpi-1.10.1/include  
-std=c11 -o CMakeFiles/hello-mpi.dir/hello-mpi.c.o   
-c /home/roberto/Workspace/robertodr/cmake-recipes/Chapter03/recipe-0016/c-example/hello-mpi.c
```
and the link line is:
```
/nix/store/j1yn1np5g2vgm5yp8qmqg67x8riwy2kr-gcc-wrapper-5.4.0/bin/gcc     
CMakeFiles/hello-mpi.dir/hello-mpi.c.o  -o hello-mpi -rdynamic -lmpi
```
Whereas the wrapper tells me:
```
-I/nix/store/8f1nmsd4cw7sdk8xrssmkk9zbq26pc2j-openmpi-1.10.1/include -pthread
```
for the compile line and
```
-pthread -Wl,-rpath -Wl,/nix/store/8f1nmsd4cw7sdk8xrssmkk9zbq26pc2j-openmpi-1.10.1/lib -Wl,--enable-new-dtags -L/nix/store/8f1nmsd4cw7sdk8xrssmkk9zbq26pc2j-openmpi-1.10.1/lib -lmpi
```
for the link line

## Question 
This is the same for C and C++ (and most likely for Fortran too) You can see that some of the wrapper options have disappeared, both for compiling and linking. What is the best practice here? Reset the compiler to the wrapped version discovered by CMake?

**Comment by bast** [comment]
I am not sure I fully understand the problem but I find it more natural and intuitive to compile with the wrapped compilers. If we use the wrapped compilers, do you see a possible issue?

**Comment by robertodr** [comment]
No issue, just making sure that that is the correct way of doing it :smile_cat: I'll close this issue.
