### ISSUE TITLE
Make sure we do not require ninja-kitware

### ISSUE THREAD

**Issue by bast** [bast/cmake-recipes#266]
This should be optional. I think perhaps the local testing defaults to it and this should rather default to Unix Makefiles.

**Comment by bast** [comment]
Do we really require it somewhere else except when defaulting to it in local tests?

**Comment by robertodr** [comment]
This specific version of Ninja is only required if you want to build Fortran code. C/C++ are fine with vanilla Ninja. We can mention in TypeCloud this fact and drop it in the testing.

**Comment by bast** [comment]
It would be good to minimize non-vanilla dependencies. But we also default to Ninja for local testing: https://github.com/bast/cmake-recipes/blob/master/testing/env.py#L22-L23

Can we change that to Unix Makefiles?

**Comment by robertodr** [comment]
Agreed! Let's drop Ninja locally, but can we keep it on Travis?

**Comment by bast** [comment]
Yes, I would like to keep it on Travis.
