### ISSUE TITLE
Use GNUInstallDirs

### ISSUE THREAD

**Issue by bast** [bast/cmake-recipes#269]
Currently not used in recipes 9/1, 9/2, 10/1, 13/1-3.

**Comment by robertodr** [comment]
Chapter 13 complies in #268

**Comment by robertodr** [comment]
I'm not so sure how clear it would be for the reader if we do it this way.

**Comment by bast** [comment]
Let's perhaps mention it in "there's more". Because people will not read it linearly but jump right into some examples I believe.

**Comment by robertodr** [comment]
I agree with the jumping. Let's mention it under "There's more"
