### ISSUE TITLE
Transfer chapter structure to TypeCloud

### ISSUE THREAD

**Issue by bast** [bast/cmake-recipes#27]
Not really this repo related but just to have overview of who is doing what.

**Comment by bast** [comment]
Before transferring everything I want to make sure that we have the structure right first: I have some questions about the Level and Skills learned which we have in the chapter structure but not in the TypeCloud yet. Will ask this over email.

**Comment by robertodr** [comment]
Everything transferred now. Plus all tentative recipes added as issues.
