### ISSUE TITLE
GoogleTest recipe is probably brittle

### ISSUE THREAD

**Issue by bast** [bast/cmake-recipes#276]
Consider using approach outlined in https://crascit.com/2015/07/25/cmake-gtest/.

**Comment by robertodr** [comment]
Interesting. I guess there should be one recipe popularizing the approach under chapter 7.

**Comment by bast** [comment]
It's an interesting alternative to the superbuild. This way one can have external projects that can be add_subdirectoried, without doing the superbuild.

**Comment by bast** [comment]
What I don't like in our current GoogleTest recipe are the explicit paths and suffixes. The approach above hides everything nicely.

**Comment by robertodr** [comment]
If the external project correctly produces a `*Config.cmake` file, then there is no problem with hardcoded paths (see the FFTW superbuild).

**Comment by bast** [comment]
Here is a compact solution: https://github.com/bast/gtest-demo
