### ISSUE TITLE
I think we should use LANGUAGES inside project()

### ISSUE THREAD

**Issue by bast** [bast/cmake-recipes#279]
It's optional but makes it easier to read and understand for people who do not know CMake.

https://cmake.org/cmake/help/v3.0/command/project.html

**Comment by TheErk** [comment]
Yes and sometimes you need it.
Like when you don't want ANY language at all.
This may be the case when you don't need to compile anything.

**Comment by bast** [comment]
We have examples without any language and it worked with `project(foo NONE)` but `project(foo LANGUAGES NONE)` is better. As you write, docs suggest that `project(foo LANGUAGES)` should work too but I think `project(foo LANGUAGES NONE)` is clearest.
