### ISSUE TITLE
Draft "Cross-compiling from Linux to Windows"

### ISSUE THREAD

**Issue by bast** [bast/cmake-recipes#295]
Just collecting notes here.

Experimenting with https://github.com/mxe/mxe. Compilation of cross-compilers take a long time so either we cache or prepare binaries or we don't test automatically.

**Comment by bast** [comment]
Seems to work. Will go for a simple example, both C++ and Fortran, as well as an OpenMP example.

**Comment by TheErk** [comment]
Did you try to apt install already compiled mingw64 binaries?
https://mingw-w64.org/doku.php/download
they provide ready to use linux-->windows cross compilers.

Nevertheless thank you for the MXE ref. it looks great.

**Comment by bast** [comment]
I haven't tried that - I am on Arch Linux. But compiling MXE from sources was smooth and then it really works like a charm.

**Comment by bast** [comment]
But good that you pointed out apt packages. This means we should be able to test this on Travis.

**Comment by bast** [comment]
Finally drafted.
