### ISSUE TITLE
Implement expected failure functionality in CI

### ISSUE THREAD

**Issue by bast** [bast/cmake-recipes#33]
Some of the failing builds, fail the whole CI. But maybe we want to show that some stuff doesn't work. How can we implement an "expected failure" behavior?

Taken from #2.

**Comment by robertodr** [comment]
I think the `config.yml` (or `menu.yml`, name that I prefer :smile_cat:) we can have a boolean `expect_fail` section. We would then change return code of the sub-job within the CI script, in case a failure is expected.

**Comment by bast** [comment]
Just that we draft this well: what are the expected failures that you expect :-) ? What are the use cases? Then we can draft a good UI for that situation.

**Comment by bast** [comment]
For instance: visual studio and Fortran, or something working on Travis but failing on Appveyor? Or working on Linux but failing on Mac? Is it this what you had in mind?

**Comment by robertodr** [comment]
That's exactly it :wink:

**Comment by bast** [comment]
Do we want a skip functionality? Or should everything be run and errors rather then ignored?

**Comment by robertodr** [comment]
I prefer to have everything run.
