### ISSUE TITLE
Unmet dependencies on AppVeyor

### ISSUE THREAD

**Issue by robertodr** [bast/cmake-recipes#35]
Many recipes currently fail because of unmet dependencies:
- Boost
- Eigen
- HDF5
- MPI
- BLAS
- LAPACK

**Comment by robertodr** [comment]
This will come with #38

**Comment by robertodr** [comment]
The unmet dependencies on Travis have been resolved. There are lingering build issues:
- when using Ninja on Linux
- on Mac OS X.
I'll rename this to _Unmet dependencies on AppVeyor" and split up the lingering issues for Travis into two separate issues.

**Comment by robertodr** [comment]
By the way, I'm trying to learn how to spin a Windows VM in Azure Cloud. Then I can play around a bit more confidently.

**Comment by bast** [comment]
Should we close this and go for more fine-grain from here on for Appveyor?

**Comment by robertodr** [comment]
We could use `vcpkg` to install deps on AppVeyor.

**Comment by bast** [comment]
Nice find!

**Comment by robertodr** [comment]
Late night Google-ing

**Comment by bast** [comment]
I am closing this - will open separate tickets with issues later today. I think we need more fine-grain for Appveyor issues.

**Comment by robertodr** [comment]
Open up a PR (even WIP) when you feel comfortable. I will start putting in some effort starting tomorrow.
