### ISSUE TITLE
Make `menu.yml` mandatory

### ISSUE THREAD

**Issue by bast** [bast/cmake-recipes#36]
Requires #34 to be merged.

**Comment by bast** [comment]
@robertodr what if there is nothing to export, nothing to define, no expected failures and nothing to skip? Do we want to require an empty menu file? One option would be to have the menu files one level higher, thus removing the language-example implicitness. In the menu we would list all examples to be run and also describe definitions and exceptions. Or we really keep it at example level.

**Comment by robertodr** [comment]
I would keep it at the example level and have every example explicitly list what's needed, _i.e._ compilers are always explicitly specified. I know it is redundant, but then all dependencies are close to the consumers (sort of)

**Comment by robertodr** [comment]
All directories now have a `menu.yml`. You can close this one :smiley: Most likely we have another iteration over the build specification menu in the future.

**Comment by robertodr** [comment]
Closing this. I am opening a new issue to discuss the contents of `menu.yml`
