### ISSUE TITLE
Draft "Discovering the instruction set"

### ISSUE THREAD

**Issue by bast** [bast/cmake-recipes#51]

**Comment by robertodr** [comment]
This Fortran use case might be an interesting example. 

[HANDE](https://github.com/hande-qmc/hande) uses the [POPCNT](http://www.felixcloutier.com/x86/POPCNT.html) to count how many orbitals in a determinant are occupied. This function comes in three flavors:

1. Fortran 2008 intrinsic, whose implementation is compiler-dependent and might be underperformant in certain cases.
2. An implementation in [HANDE](https://github.com/hande-qmc/hande) which uses a branchless algorithm (probably divide-and-conquer)
3. The CPU intrinsic directive `popcnt` which is much faster than both of the above alternatives.

**Comment by bast** [comment]
Currently un-assigning to mark work in progress but might re-assign to myself.

**Comment by robertodr** [comment]
https://cmake.org/cmake/help/v3.10/command/cmake_host_system_information.html#command:cmake_host_system_information

**Comment by bast** [comment]
Is solved. Closing to focus on remaining issues.
