### ISSUE TITLE
Allow CI to also execute code so that we can check output on different platforms

### ISSUE THREAD

**Issue by bast** [bast/cmake-recipes#55]

**Comment by robertodr** [comment]
Yes, I was thinking exactly the same. How about adding tests with CTest? We don't need to explain them in the recipes until we get to the appropriate chapter

**Comment by bast** [comment]
I like the idea. It is consistent and also gives flexibility, simply `make test` and the good thing is that we then have full flexibility in each recipe to define whatever we want to test.
