### ISSUE TITLE
Update recipe "Detecting the Python Library" on TypeCloud

### ISSUE THREAD

**Issue by robertodr** [bast/cmake-recipes#57]
Recipe 12 (Python library) and recipe 17 (Eigen) have been modified. TypeCloud should be updated.

**Comment by bast** [comment]
Eigen part followed up in #156.

**Comment by bast** [comment]
The Python one is now Chapter03/recipe-02.

**Comment by bast** [comment]
I was about to update the TypeCloud part but when looking at the recipe: for simplicity, should we not rather have only one c file that works with both Python 2 and 3? Or is the point to demonstrate that you can detect the Python version?

**Comment by robertodr** [comment]
I don't think you can have just one C file, some functions do not exist/have different signature.

**Comment by bast** [comment]
By that you mean a different signature in `Python.h`?

**Comment by robertodr** [comment]
Yes, that's what I mean. Maybe those can be unified with preprocessor variables... I think I wanted to show how to use those variables in conditionals though.

**Comment by bast** [comment]
OK I see. This is good then. We should note these alternatives in the text. Do you prefer to go over the TC recipe or do you prefer me updating it? Advantage: new perspective, disadvantage: possibly I miss some point.

**Comment by robertodr** [comment]
Go for it! Remember to also "mark draft as complete" after saving.

**Comment by bast** [comment]
This is now done.
