### ISSUE TITLE
Book introduction

### ISSUE THREAD

**Issue by robertodr** [bast/cmake-recipes#58]
It would be nice to give statistics on CMake usage in the introduction. Datasets we can use:
- Stackoverflow datasets: https://www.kaggle.com/stackoverflow/datasets
I think the want we want to sample for statistics is this one: https://www.kaggle.com/stackoverflow/stacklite
- Google trends

**Comment by TheErk** [comment]
You can have a look to Open Hub language compare tool as well:
https://www.openhub.net/languages/compare

compare e.g. CMake bvs Autoconf:
https://www.openhub.net/languages/compare?utf8=%E2%9C%93&measure=commits&language_name%5B%5D=cmake&language_name%5B%5D=autoconf&language_name%5B%5D=-1&language_name%5B%5D=-1&language_name%5B%5D=-1&commit=Update

**Comment by bast** [comment]
Closing. We track book issues now in a separate document.
