### ISSUE TITLE
Advocate modern CMake practices throughout the book

### ISSUE THREAD

**Issue by robertodr** [bast/cmake-recipes#59]
- Use _targets_ and _properties_
- Do **not** use `CMAKE_<LANG>_FLAGS_<CONFIG>`. See [here](https://stackoverflow.com/a/23995391/2528668)
- Do **not** use `link_directories`, `include_directories`, `add_compile_options`,  `link_libraries`
- Present the analogy between C++ objects and CMake targets.
- This presentation by [Daniel Pfeifer](https://www.youtube.com/watch?v=bsXLMQ6WgIk) sums up all these things very neatly. [Slides on GitHub](https://github.com/boostcon/cppnow_presentations_2017/blob/master/05-19-2017_friday/effective_cmake__daniel_pfeifer__cppnow_05-19-2017.pdf)

**Comment by TheErk** [comment]
I totally agree and I'd like to add `target_source`
see: https://crascit.com/2016/01/31/enhanced-source-file-handling-with-target_sources/

**Comment by robertodr** [comment]
@TheErk I think we started using it in some of the later recipes, but haven't "upgraded" the basic recipes yet.

**Comment by bast** [comment]
Agree, we will do this in the second pass through the recipes. It is a really nice design pattern. The goal will be to motivate to localize scope and hide internals to simplify the global scope and decouple order.

**Comment by TheErk** [comment]
Ok thanks.

**Comment by TheErk** [comment]
As a reminder during the sweep through the recipe you can check whether IMPORTED targets may be used. See PR #224

**Comment by bast** [comment]
Imported targets are also now tracked in #225.

**Comment by bast** [comment]
Thanks again for good suggestion. We are closing this issue but we will implement these in the book.
