### ISSUE TITLE
Numbering of recipes: per chapter instead of global index?

### ISSUE THREAD

**Issue by bast** [bast/cmake-recipes#63]
Should we perhaps number recipes only within chapters? For book readers they will be easy to find since they can search by chapter. For instance `chapter-9/recipe-4` would be 4th recipe in chapter 9. This would spare us the work and possible breakage of renumbering recipes. Especially if we draft recipes across chapters and not chapter by chapter.

**Comment by bast** [comment]
Also let us assume that one day there is a second edition and we add few recipes, could be nice to be able to add few and remove some without renumbering everything.

**Comment by robertodr** [comment]
Can you give an example of how numbering would work in the second edition? I didn't quite get it from what you wrote. It sound like a good idea, however. I still have to re-number recipes in Chapter 3 though :sweat_smile:

**Comment by bast** [comment]
I meant adding a recipe in chapter 4 would not require to renumber all recipes in chapter 5 and later.

**Comment by robertodr** [comment]
OK, yeah I see. Let's do it like that. I'll re-number recipes in Chapter 3 accordingly and then we can close this and #44

**Comment by robertodr** [comment]
Closed by #67
