### ISSUE TITLE
Travis CI on Mac OS X failures

### ISSUE THREAD

**Issue by robertodr** [bast/cmake-recipes#64]
Builds on Travis CI for Mac OS X are currently failing. Two problems:
- Apple Clang does not support OpenMP. Some recipes in chapter 3 require OpenMP. We need the expected failure section in `menu.yml` for this.
- The implementation of UUID seems not to be the same as on Linux, specifically the `uuid_generate_time_safe` is not there. I'll fix it by using `uuid_generate` in the source code.

**Comment by bast** [comment]
Copy that. Working on the expected failure section.

**Comment by robertodr** [comment]
It's going to be hard to debug Mac OS X builds, given the _de facto_ permanent backlog on Travis CI...

**Comment by bast** [comment]
Travis green and happy. Closing this one.
