### ISSUE TITLE
Draft "Probing compiler flags"

### ISSUE THREAD

**Issue by robertodr** [bast/cmake-recipes#78]

**Comment by robertodr** [comment]
@bast what did we mean with this?

**Comment by bast** [comment]
I think what we meant is to check whether a flags is available by trying to compile a code snippet at configure time. Example is -xHost. Related to #76.

**Comment by robertodr** [comment]
Note: `check_fortran_compiler_flag` was introduced in CMake 3.3 Should we bump up CMake requirement or note in the recipe that the Fortran example requires a higher version of CMake?

**Comment by robertodr** [comment]
I'm planning on describing how to check that sanitizers (address, memory, thread and undefined behavior) are available for the C, C++ and Fortran.

**Comment by bast** [comment]
Yes for the bump. I think it is good to demo modern features.
