### ISSUE TITLE
Draft "Fine-tuning configuration and compilation with generator expressions"

### ISSUE THREAD

**Issue by robertodr** [bast/cmake-recipes#79]

**Comment by robertodr** [comment]
I plan to show how to convert conditionals of the form:
```
if(USE_THIS)
  target_<command>(...)
endif()
```
to use generator expressions:
```
target_<command>(... <generator-expression>)
```

**Comment by bast** [comment]
That's really cool because then I learn something new since I am new to generator expressions :-)
