### ISSUE TITLE
Draft "Probing an external library"

### ISSUE THREAD

**Issue by robertodr** [bast/cmake-recipes#85]

**Comment by robertodr** [comment]
@bast I am unsure what we meant by this when we wrote the outline :sweat_smile:

**Comment by bast** [comment]
I think what we meant is not only finding the library by its path or file signature, but also probing that it actually works at configure time before building and linking the code. Example here could be a library that supports 64 bit integers which could be probed at configure time.

**Comment by robertodr** [comment]
A 64-bit MPI example would fit nicely here, no?

**Comment by bast** [comment]
Maybe a BLAS library could be more library-like than MPI. MPI example would be good but I am not sure it is a library in the library sense :-)

**Comment by robertodr** [comment]
Yes. This can be closed.
