### ISSUE TITLE
Draft "Building C/C++ and Fortran projects with CMake and iso_c_binding"

### ISSUE THREAD

**Issue by robertodr** [bast/cmake-recipes#99]

**Comment by bast** [comment]
Closing this issue. We wish to track issues with a shorter time horizon and only keep issues where we discuss things, track known problem, track ideas, and track ongoing work.Closing this issue. We wish to track issues with a shorter time horizon and only keep issues where we discuss things, track known problem, track ideas, and track ongoing work.
